#include "SplashScreen.h"
#include "ui_SplashScreen.h"  // This file is generated by the UIC tool

SplashScreen::SplashScreen(QWidget *parent)
    : QWidget(parent), ui(new Ui::SplashScreen)  // Initialize the UI pointer
{
    ui->setupUi(this);  // Set up the UI from the .ui file
    setWindowFlags(Qt::FramelessWindowHint | Qt::WindowStaysOnTopHint);
    setFixedSize(size()); // Set the fixed size to match the UI size
    setWindowIcon(QIcon(":/Content/Content/Images/Icons/novusblack.ico"));

    // Set the image for the splash screen
    QPixmap pixmap(":/Content/Content/Images/Logos/novus white text.png");
    if (pixmap.isNull()) {
        qWarning() << "Failed to load splash screen image.";
    }
    QLabel *splashImageLabel = new QLabel(this);
    splashImageLabel->setPixmap(pixmap);

    // Adjust image label size and position
    splashImageLabel->setGeometry(0, 0, 931, 201);  // Adjust dimensions if needed
    splashImageLabel->move((width() - splashImageLabel->width()) / 2, (height() - splashImageLabel->height()) / 2);

    // Ensure the FilesLoadingLabel is accessible and update its properties
    if (ui->FilesLoadingLabel) {
        ui->FilesLoadingLabel->setText("Loading files...");
    } else {
        qWarning() << "FilesLoadingLabel is not initialized.";
    }
}

SplashScreen::~SplashScreen()
{
    delete ui;
}

void SplashScreen::updateLoadingStatus(const QString &statusText)
{
    if (ui->FilesLoadingLabel) {
        ui->FilesLoadingLabel->setText(statusText);
    } else {
        qWarning() << "FilesLoadingLabel is not initialized.";
    }
}
